name: Elixir CI

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.8.2
            otp: 22
          - elixir: 1.9.4
            otp: 22
          - elixir: 1.10.4
            otp: 23
          - elixir: 1.11.4
            otp: 24.1
          - elixir: 1.12.3
            otp: 24.1
          - elixir: 1.12.3
            otp: 24.1
            unlock: true

    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}} (${{matrix.unlock}})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - run: mix deps.get
      - run: mix deps.unlock --all --check-unused
        if: ${{ matrix.unlock }}
      - run: mix test

  lint:
    name: Run lint & format checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: '1.12.3' # Define the elixir version [required]
          otp-version: '24.1' # Define the OTP version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - run: mix deps.get
      - run: mix format --check-formatted
